name: Build and Release
on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.23
          ldflags: "-s -w"
          binary_name: localsend
          build_flags: "-trimpath"
          md5sum: false
          sha256sum: true
