name: Build and Release
on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.23
          ldflags: "-s -w -X github.com/0w0mewo/localsend-cli/cmd.version=${{ vars.VERSION }}"
          binary_name: localsend
          build_flags: "-trimpath"
          pre_command: |
            export CGO_ENABLE=0
          md5sum: false
          sha256sum: true
